version: '2'
services:
    mepspring-app:
        image: mepspring
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mepspring-mysql:3306/mepspring?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mepspring-mysql:
        extends:
            file: mysql.yml
            service: mepspring-mysql
